server:
  port: 6060
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdata?createDatabaseIfNotExist=true
    username: root
    password: Coder@9505
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

logging:
  level:
    org:
      springframework:
        security: DEBUG
