server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
          filters:
            - name: AuthenticationFilter
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
          filters:
            - name: AuthenticationFilter
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            - name: AuthenticationFilter
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - name: AuthenticationFilter
