server:
  port: 9090
spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://localhost:3306/movies?createDatabaseIfNotExist=true
    username: root
    password: Coder@9505
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}